### ISSUE TITLE
フォーク PR でも CI を回す

### ISSUE THREAD

**Issue by tomoya** [times-yasunori/awesome-yasunori#108]
どうやら ci.yaml に on: push しか書いてないのが原因の模様。
フォークPR だと push されるのはこのリポジトリではないため、push トリガーにヒットしないと思われる。

**Comment by teramako** [comment]
GitHubの案内に従って作ったActionだと以下のようになっていました。
```yaml
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
```
`pull_request` がそれにあたりそうですね。

**Comment by akirak** [comment]
一般的には、 `pull_request` にはブランチを指定せず、 `push` はデフォルトブランチ（awesome-yasunoriでは `main`）のみにすると思います。

[nix-emacs-ci](https://github.com/purcell/nix-emacs-ci/blob/master/.github/workflows/test.yml) のCIでは、以下のように指定されています。

```yaml
on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'
    branches:
      - master
```
