### ISSUE TITLE
Slack からコピーしたテキストで、AY Syntax を生成する API

### ISSUE THREAD

**Issue by tomoya** [times-yasunori/awesome-yasunori#150]
`POST /awesome/from-slack-text` のようなエンドポイントで実現する。 

## Slackからコピーしたテキスト例（INPUT）
```
tomoya
  21:06
えっ、yasunori 知らないの？
↑
yasuhara
```

## 出力

以下のように出力される

```toml
[[yasunori]]
id = <次の番号>
title = "えっ、yasunori 知らないの？" # 本文1行目（テキストの3行目）
date = "2024-11-02" # APIを実行した日付でいい
at = "vim-jp #times-yasunori" # 固定でよい
senpan = "tomoya" # 1行目のユーザー名
content = """
えっ、yasunori 知らないの？
↑
yasuhara
"""
meta = "" # とりあえず空でいい
```
